export const ROUTE_PATHS = {
    HOME: "/",
    ABOUT_US: "/about-us",
    VISION: "/vision",
    CONTACT_US: "/contactus",
    KSHETRA: "/kshetra",
    KSHETRA_LANDING: "/open-plots-in-shankarpally/kshetra",
    PLOTS_SHANKARPALLY: "/plots-in-shankarpally",
    PLOTS_MAHESHWARAM: "/plots-in-maheshwaram",
    PLOTS_SULTANPUR: "/plots-in-sultanpur-hyderabad",
    TRANQUIL_VALLEY: "/tranquilvalley",
    TRANQUIL_VALLEY_LANDING: "/open-plots-in-maheshwaram/tranquilvalley",
    SUNRISE_CITY: "/sunrisecity",
    SUNRISE_CITY_LANDING: "/plots-in-sultanpur-hyderabad/sunrisecity",
    SPRING_CITY: "/springcity",
    SPRING_CITY_PROJECT: "/projects/springcity",
    PROJECTS: "/projects",
    COMPLETED_PROJECTS: "/projects/completedProjects",
    ONGOING_PROJECTS: "/projects/onGoingProjects",
    BLOGS: "/blogs",
    BLOG_CONTENT: "/blog/:slug",
    BLOG_CATEGORY: "/blog/category/:name",
    CAREERS: "/careers",
    BLOG3: "/blog3",
    ISO_CERTIFIED: "/iso-certified",
    PRIVACY_POLICY: "/privacy-policy"
  };